# Airbnb Data Cleaning with Pandas

This notebook focuses on cleaning an Airbnb listings dataset using Python and Pandas.

The cleaning process includes:

- Standardizing column names
- Fixing incorrect data types
- Cleaning currency fields (price, service_fee)
- Handling missing values
- Removing duplicate listings
- Filtering unrealistic values (minimum_nights, availability_365)
- Converting date columns

The final dataset contains **72,895 rows and 24 columns** and is ready for exploratory data analysis.

## 1. Import Libraries
## 2. Load Dataset

In [1]:
import pandas as pd
data = pd.read_csv("Airbnb_Open_Data.csv", low_memory=False)

In [2]:
## 2. Load Dataset
data

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [3]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

## 3. Column Name Cleaning

In [4]:
data.columns = data.columns.str.strip().str.replace(' ','_')
data.columns = data.columns.str.lower()
data.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count',
       'availability_365', 'house_rules', 'license'],
      dtype='str')

In [5]:
data.dtypes

id                                  int64
name                                  str
host_id                             int64
host_identity_verified                str
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
lat                               float64
long                              float64
country                               str
country_code                          str
instant_bookable                   object
cancellation_policy                   str
room_type                             str
construction_year                 float64
price                                 str
service_fee                           str
minimum_nights                    float64
number_of_reviews                 float64
last_review                           str
reviews_per_month                 float64
review_rate_number                float64
calculated_host_listings_count    float64
availability_365                  float64
house_rules                           str
license                               str
dtype: object

## 4. Data Type Corrections

In [6]:
data['instant_bookable'] = data['instant_bookable'].astype('bool')
data['construction_year'] = data['construction_year'].astype('Int64')
data['price'] = data['price'].str.strip().str.replace('$','',regex=False).str.replace(',','').astype('Int64')
data['service_fee'] =  data['service_fee'].str.strip().str.replace(',','').str.replace('$','',regex=False).astype('Int64')
data['minimum_nights'] = data['minimum_nights'].astype('Int64')
data['calculated_host_listings_count'] = data['calculated_host_listings_count'].astype('Int64')
data['availability_365'] = data['availability_365'].astype('Int64')
data['last_review'] = pd.to_datetime(data['last_review'], format = '%m/%d/%Y')
data['number_of_reviews'] = data['number_of_reviews'].astype('Int64')

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   name                            102349 non-null  str
 2   host_id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host_name                       102193 non-null  str
 5   neighbourhood_group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country_code                    102468 non-null  str
 11  instant_bookable                102599 non-null  bool
 12  cancellation_policy             102523 non-null  str
 13  room_type                       102599 non-null  str
 14  construction_year               102385 non-null  Int64
 15  price                           102352 non-null  Int64
 16  service_fee                     102326 non-null  Int64
 17  minimum_nights                  102190 non-null  Int64
 18  number_of_reviews               102416 non-null  Int64
 19  last_review                     86706 non-null   datetime64[us]
 20  reviews_per_month               86720 non-null   float64
 21  review_rate_number              102273 non-null  float64
 22  calculated_host_listings_count  102280 non-null  Int64
 23  availability_365                102151 non-null  Int64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: Int64(7), bool(1), datetime64[us](1), float64(4), int64(2), str(11)
memory usage: 20.4 MB

In [8]:
data

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,...,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,193,10,9,2021-10-19,0.21,4.0,6,286,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,28,30,45,2022-05-21,0.38,4.0,2,228,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,124,3,0,NaT,NaN,5.0,1,352,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,74,30,270,2019-07-05,4.64,4.0,1,322,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,41,10,9,2018-11-19,0.10,3.0,1,289,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,169,1,0,NaT,NaN,3.0,1,227,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,167,1,1,2015-07-06,0.02,2.0,2,395,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,198,3,0,NaT,NaN,5.0,1,342,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,109,2,5,2015-10-11,0.10,3.0,1,386,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,206,1,0,NaT,NaN,3.0,1,69,NaN,NaN

In [9]:
data.isnull().sum()

id                                     0
name                                 250
host_id                                0
host_identity_verified               289
host_name                            406
neighbourhood_group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country_code                         131
instant_bookable                       0
cancellation_policy                   76
room_type                              0
construction_year                    214
price                                247
service_fee                          273
minimum_nights                       409
number_of_reviews                    183
last_review                        15893
reviews_per_month                  15879
review_rate_number                   326
calculated_host_listings_count       319
availability_365                     448
house_rules                        52131
license                           102597
dtype: int64

In [10]:
data.drop(columns = ['license'], inplace = True)
data.drop(columns = ['house_rules'], inplace = True)

In [11]:
data.isnull().sum()

id                                    0
name                                250
host_id                               0
host_identity_verified              289
host_name                           406
neighbourhood_group                  29
neighbourhood                        16
lat                                   8
long                                  8
country                             532
country_code                        131
instant_bookable                      0
cancellation_policy                  76
room_type                             0
construction_year                   214
price                               247
service_fee                         273
minimum_nights                      409
number_of_reviews                   183
last_review                       15893
reviews_per_month                 15879
review_rate_number                  326
calculated_host_listings_count      319
availability_365                    448
dtype: int64

## 5. Handling Missing Values

In [12]:
data = data.dropna(subset=[
'price',
'service_fee',
'minimum_nights',
'availability_365',
'lat',
'long',
'neighbourhood',
'neighbourhood_group'
])

In [13]:
data.isnull().sum()

id                                    0
name                                221
host_id                               0
host_identity_verified              261
host_name                           386
neighbourhood_group                   0
neighbourhood                         0
lat                                   0
long                                  0
country                             518
country_code                        105
instant_bookable                      0
cancellation_policy                  62
room_type                             0
construction_year                   174
price                                 0
service_fee                           0
minimum_nights                        0
number_of_reviews                   127
last_review                       15510
reviews_per_month                 15509
review_rate_number                  297
calculated_host_listings_count      319
availability_365                      0
dtype: int64

## 6. Removing Duplicates

In [14]:
data['id'].duplicated().sum()

np.int64(532)

In [15]:
data = data.drop_duplicates(subset = ['id'])

In [16]:
data['id'].duplicated().sum()

np.int64(0)

In [17]:
data['price'].describe()

count      100709.0
mean      625.28496
std      331.690864
min            50.0
25%           340.0
50%           625.0
75%           913.0
max          1200.0
Name: price, dtype: Float64

In [18]:
data['price'].sort_values(ascending = False).head(10)

86099    1200
99860    1200
64304    1200
45784    1200
24028    1200
75053    1200
53366    1200
33607    1200
68496    1200
33902    1200
Name: price, dtype: Int64

## 7. Outlier Detection and Cleaning

In [19]:
data['minimum_nights'].describe()

count     100709.0
mean      8.069388
std      28.657204
min        -1223.0
25%            2.0
50%            3.0
75%            5.0
max         5645.0
Name: minimum_nights, dtype: Float64

In [20]:
data = data[(data['minimum_nights']>=1) & (data['minimum_nights']<=30)]

In [21]:
data['minimum_nights'].describe()

count     99035.0
mean     6.521725
std      9.336091
min           1.0
25%           1.0
50%           3.0
75%           5.0
max          30.0
Name: minimum_nights, dtype: Float64

In [22]:
data['availability_365'].describe()

count       99035.0
mean     140.142949
std      135.353975
min           -10.0
25%             3.0
50%            94.0
75%           267.0
max          3677.0
Name: availability_365, dtype: Float64

In [23]:
data = data[(data['availability_365']>=0) & (data['availability_365']<=365)]

In [24]:
data['availability_365'].describe()

count       95949.0
mean     133.640538
std      129.702786
min             0.0
25%             2.0
50%            90.0
75%           253.0
max           365.0
Name: availability_365, dtype: Float64

In [25]:
data['service_fee'].describe()

count       95949.0
mean     125.175718
std       66.343946
min            10.0
25%            68.0
50%           125.0
75%           183.0
max           240.0
Name: service_fee, dtype: Float64

In [26]:
data['availability_365'].describe()

count       95949.0
mean     133.640538
std      129.702786
min             0.0
25%             2.0
50%            90.0
75%           253.0
max           365.0
Name: availability_365, dtype: Float64

In [27]:
data['review_rate_number'].describe()

count    95679.000000
mean         3.287273
std          1.278551
min          1.000000
25%          2.000000
50%          3.000000
75%          4.000000
max          5.000000
Name: review_rate_number, dtype: float64

In [28]:
data['number_of_reviews'].describe()

count      95823.0
mean     27.380274
std      49.087723
min            0.0
25%            1.0
50%            7.0
75%           31.0
max         1024.0
Name: number_of_reviews, dtype: Float64

## 8. Unique Control

In [29]:
data['id'].nunique() , data['id'].count()

(95949, np.int64(95949))

## 9. Negative Price Check

In [30]:
(data['price'] < 0).sum()

np.int64(0)

## 10. Final Dataset Overview

In [31]:
data.shape

(95949, 24)

In [32]:
data.info()

<class 'pandas.DataFrame'>
Index: 95949 entries, 0 to 102043
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              95949 non-null  int64
 1   name                            95740 non-null  str
 2   host_id                         95949 non-null  int64
 3   host_identity_verified          95712 non-null  str
 4   host_name                       95572 non-null  str
 5   neighbourhood_group             95949 non-null  str
 6   neighbourhood                   95949 non-null  str
 7   lat                             95949 non-null  float64
 8   long                            95949 non-null  float64
 9   country                         95450 non-null  str
 10  country_code                    95859 non-null  str
 11  instant_bookable                95949 non-null  bool
 12  cancellation_policy             95898 non-null  str
 13  room_type                       95949 non-null  str
 14  construction_year               95800 non-null  Int64
 15  price                           95949 non-null  Int64
 16  service_fee                     95949 non-null  Int64
 17  minimum_nights                  95949 non-null  Int64
 18  number_of_reviews               95823 non-null  Int64
 19  last_review                     81553 non-null  datetime64[us]
 20  reviews_per_month               81554 non-null  float64
 21  review_rate_number              95679 non-null  float64
 22  calculated_host_listings_count  95659 non-null  Int64
 23  availability_365                95949 non-null  Int64
dtypes: Int64(7), bool(1), datetime64[us](1), float64(4), int64(2), str(9)
memory usage: 18.3 MB

In [33]:
data

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,...,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,2020,966,193,10,9,2021-10-19,0.21,4.0,6,286
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,2007,142,28,30,45,2022-05-21,0.38,4.0,2,228
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,2005,620,124,3,0,NaT,NaN,5.0,1,352
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,2005,368,74,30,270,2019-07-05,4.64,4.0,1,322
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,2009,204,41,10,9,2018-11-19,0.10,3.0,1,289
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102032,57353610,Spacious Room w/ 2 Bed,69037598918,unconfirmed,Christine,Queens,Bayside,40.75047,-73.75349,United States,...,2007,103,21,7,40,2019-06-23,1.51,1.0,5,148
102040,57358028,"Room in Queens, NY, near LGA.",56457739998,verified,Sonia,Queens,East Elmhurst,40.76245,-73.87938,United States,...,2022,982,196,1,239,2019-06-29,8.58,2.0,2,361
102041,57358580,Cozy home away from home,60176837202,verified,NaN,Queens,Edgemere,40.59380,-73.77373,United States,...,2020,946,189,1,76,2019-06-27,2.84,1.0,1,324
102042,57359133,Central Park Views - Private Room & Bathroom,68411243647,verified,NaN,Manhattan,Upper West Side,40.79712,-73.96117,United States,...,2012,706,141,1,4,2017-08-15,0.14,4.0,1,0
102043,57359685,Ultimate 50th Floor Downtown Penthouse - 4000...,95625271612,verified,NaN,Manhattan,SoHo,40.72318,-74.00223,United States,...,2020,1043,209,2,21,2019-07-01,0.74,4.0,2,343

All listing IDs are unique, confirming that duplicate records were successfully removed.

## Final Dataset Summary

After cleaning and validation:

- Rows: 72,895
- Columns: 24
- Duplicate listings removed
- Unrealistic values filtered
- Data types corrected
- Dataset ready for exploratory data analysis